ADBDEV-6257: Fix pg_dump incorrect cleanup for external tables
arenadata/db pull request #1045
Opened 2024-09-10 11:29 UTC by silent-observer

Fix pg_dump incorrect cleanup for external tables

Fixes issue #1025. DROP EXTERNAL TABLE in pg_dump output had incorrect syntax,
this patch fixes the typo.

Co-authored-by: eshkinkot \<eshkinkot@gmail.com\>

2024-09-10 12:01 UTC, BenderArenadata commented
Allure report https://allure.adsw.io/launch/79870

2024-09-10 13:50 UTC, bandetto commented
Small note: please escape `<` symbols around "Co-authored-by:" clause with backslashes to avoid them being eaten up by markdown in PR description.

2024-09-11 07:27 UTC, BenderArenadata commented
Allure report https://allure.adsw.io/launch/79931

2024-09-12 04:37 UTC, whitehawk commented on src/test/regress/input/external_table.source
> +CREATE EXTERNAL TABLE issue_1025 (a int) location ('file://@hostname@@abs_srcdir@/data/no/such/place/badt1.tbl' ) format 'csv' (DELIMITER '|');
Mixed style in the test - a part of the query is in the lower case and the other part is in the upper case. I know that the code right above is written in the similar manner. But the code below is all lower-case.

So, let's do not extend the bad tradition. Better to make it in all-lower-case style.

2024-09-12 05:26 UTC, hilltracer requested changes
It looks fine. I tested the patch with the following commands:

- Create a CSV file:
```sh
echo "1|101" > ~/gpdata/tmp/test_file.csv
echo "2|102" >> ~/gpdata/tmp/test_file.csv
echo "3|103" >> ~/gpdata/tmp/test_file.csv
```

- Create the external table:
```sql
CREATE EXTERNAL TABLE public.ext_test_table
	( id integer, data integer) 
	LOCATION ('file://den-laptop/home/den/gpdata/tmp/test_file.csv')
	FORMAT 'csv' (DELIMITER '|');

SELECT * FROM ext_test_table;
```

- Dump the external table:
```sh
pg_dump -s -c -t public.ext_test_table postgres
```

2024-09-12 05:26 UTC, hilltracer commented on src/test/regress/input/external_table.source
> +CREATE EXTERNAL TABLE issue_1025 (a int) location ('file://@hostname@@abs_srcdir@/data/no/such/place/badt1.tbl' ) format 'csv' (DELIMITER '|');
Maybe better to set the schema name during table creation? As the schema name is used in subsequent command and in output file:
```sql
create external table public.issue_1025 (a int) ...
```

2024-09-12 08:05 UTC, whitehawk approved these changes

2024-09-12 08:05 UTC, hilltracer approved these changes

2024-09-12 08:10 UTC, BenderArenadata commented
Allure report https://allure.adsw.io/launch/80041

2024-09-12 10:55 UTC, merged