gpstate: added dbname and PGOPTIONS in pg_isready call
arenadata/db pull request #123
Opened 2020-10-26 13:48 UTC by t1mursadykov

When calling `gpsgate`, an error appears in the segment logs:
```
"FATAL","3D000","database ""t1mursadykov"" does not exist",,,,,,,0,,"postinit.c",955,
```
To get the segment statuses, `gpstate` calls `pg_isready`, which pings the desired host and port and returns the code that the server sent . 

To get the server state, `pg_isready` uses the `PQpingParams` function of the libpq library. Which connects to the server and returns the received return code. The documentation says thats it is not necessary to pass correct user name, password, or database name values to obtain the server status. However, if incorrect values are provided, the server logs an unsuccessful connection attempt. 

To fix this, parameters in the `pg_isready` call was added.

2020-10-26 23:45 UTC, darthunix requested changes
1. ~~`PGOPTIONS='-c gp_session_role=utility'` is a redundant modification - the warning appears because `pg_isready` without explicit database name uses current user name (`gpadmin` in most cases - and we don't have `gpadmin` database in a cluster). `utility` mode doesn't affect this behaviour.~~
Hmmm, after trying `pg_isready` to segments I've got an error that explained me why do we need `PGOPTIONS='-c gp_session_role=utility'`

> 2020-10-27 11:38:27.149853 +10,"darthunix","template1",p94034,th429100480,"::1","57630",2020-10-27 11:38:27 +10,0,,,seg0,,,,sx1,"FATAL","57P03","connections to primary segments are not allowed","This database instance is running as a primary segment in a Greenplum cluster and does not permit direct connections.","To force a connection anyway (dangerous!), use utility mode.",,,,,0,,"postinit.c",1151,
2. I suggest to use `template1` instead of `postgres` database - it is possible that some customers can remove `postgres` database, but it is much less likely they remove the default template used by `create database` command.
3. All arguments in `pg_isready` use a short form, so I can suggest to replace `--dbname` with `-d`.

2020-10-27 11:52 UTC, leskin-in reviewed
Completely agree with @darthunix 's [review](https://github.com/arenadata/gpdb/pull/123#pullrequestreview-517253559). I have nothing to add.

2020-10-27 16:08 UTC, maksm90 commented
> I suggest to use template1 instead of postgres database - it is possible that some customers can remove postgres database, but it is much less likely they remove the default template used by create database command.

+1 for using `template1` instead of `postgres` but maybe it makes sense to somehow propagate database name value from outside, e.g., via special env variable? I think this question could be up at the stage of PR to upstream leaving for right now the predefined name `template1`.

2020-11-08 23:31 UTC, darthunix approved these changes

2020-11-09 09:15 UTC, maksm90 approved these changes

2020-12-30 03:37 UTC, merged