pg_rewind: avoid removing "pg_log" files
arenadata/db pull request #169
Opened 2021-03-19 07:09 UTC by maksm90

## Problem description
"pg_log" is part of excluded directory list. The semantics of exclude file/directory list is to avoid copy from source to target. But also as side effect if those files are present in target, they are removed as well.

This semantic is good for most of things but for "pg_log" directory don't wish to get them removed. Hence, adding logic to add this exception.

Backport 6f29a6f to 6X.

## Steps to reproduce

1. Increase `wal_keep_segments` up to, e.g., 1000 so that new primary doesn’t rotate its wal segments after point of divergence and hence `pg_rewind` would run well.
2. Make some modifications to DB:
  ```sql
  create table test as select i from generate_series(1, 1000) i;
  ```
3. Immediately stop primary segment:
  ```bash
  kill -QUIT <primary_postmaster_pid>
  ```
4. Check that old mirror becomes primary
5. Run `gprecoverseg -s` to restore old primary and track progress of `pg_rewind`
6. After successful completion of previous command all old files inside `pg_log` directory have to be removed.

2021-03-19 09:09 UTC, leskin-in requested changes
I suppose we should backport this change to 6X in upstream.

2021-03-19 16:23 UTC, maksm90 commented
> I suppose we should backport this change to 6X in upstream.

Yep, after discussion of this issue https://github.com/greenplum-db/gpdb/pull/11625#issuecomment-802669470

2021-03-22 00:47 UTC, Stolb27 commented
> I suppose we should backport this change to 6X in upstream.

What kind of changes do you request in this PR?

2021-03-22 05:32 UTC, maksm90 commented
> What kind of changes do you request in this PR?

I suppose, a whole patch is meant

2021-03-22 06:39 UTC, leskin-in approved these changes

2021-03-22 06:59 UTC, darthunix requested changes
I agree with https://github.com/greenplum-db/gpdb/pull/11625#issuecomment-802669470 - the implementation we backport is incorrect (https://github.com/greenplum-db/gpdb/commit/6ec6422608e3ed7d824580841dada8bdd5b8de63 is incorrect as well). We should parse configuration files to get `log_directory` value. I am not sure whether we can use [GetConfigOption() ](https://github.com/arenadata/gpdb/blob/1197a21c0313bc27557027f5bde7d3834991298f/src/backend/utils/misc/guc.c#L6631)on a frontend side, but I believe this problem can be solved.

2021-03-22 08:14 UTC, Stolb27 commented
> We should parse configuration files to get `log_directory` value.

@darthunix 
I think it is more complex task. At least because there is a lot of hardcoded places in python toolchain:

* https://github.com/greenplum-db/gpdb/blob/37fd6fa0d65780b539bd1699a39e62bc714c7be0/gpMgmt/bin/gppylib/commands/gp.py#L246
* https://github.com/greenplum-db/gpdb/blob/37fd6fa0d65780b539bd1699a39e62bc714c7be0/gpAux/gpdemo/gpsegwalrep.py#L104-L105
* etc

So let's divide bug fix and improvement

2021-03-22 08:22 UTC, darthunix commented
@Stolb27 but this backport doesn't work with a `log_directory` different from default. I don't think it is a bug fix at all.

2021-03-22 08:23 UTC, Stolb27 commented
Greenplum doesn't work at all with custom `log_directory` (have no support). I tried to say it.

2021-03-22 08:33 UTC, darthunix approved these changes
After discussion with @Stolb27 in the comments above I see, that `log_directory ` is a [hidden](https://github.com/arenadata/gpdb/blob/ADBDEV-1248/src/backend/utils/misc/guc.c#L3071) GUC (i.e. has GPDB specific `GUC_NO_SHOW_ALL` flag) and can't be changed with `gpconfig` under normal conditions. So, let's fix it as have been suggested.

2021-03-22 12:25 UTC, maksm90 commented
> ... log_directory is a hidden GUC (i.e. has GPDB specific GUC_NO_SHOW_ALL flag) and can't be changed with gpconfig under normal conditions.

More precisely, `log_directory` is [included](https://github.com/arenadata/gpdb/blob/6.15.0_arenadata15/src/backend/utils/misc/guc.c#L3067) in `DEFUNCT_OPTIONS` group, hence its external change will [have no any effect](https://github.com/arenadata/gpdb/blob/6.15.0_arenadata15/src/backend/utils/misc/guc.c#L6014-L6022).

2021-03-23 04:01 UTC, Stolb27 commented
> I suppose we confidently might propagate our change to 6X along with comment (or with assert, better yet) that our fix works while `log_directory` is declared as `DEFUNCT_OPTIONS`.

@maksm90 If we could provide such assertion, it would be great. Although, I don't think that this GUC will be changed in 6X.

2021-03-23 08:09 UTC, Stolb27 approved these changes

2021-04-20 13:01 UTC, merged