ADBDEV-1459 add behave tests runners
arenadata/db pull request #180
Opened 2021-04-16 10:00 UTC by skhomuti

Also added allure reporting

2021-05-26 13:17 UTC, Maunty commented on arenadata/scripts/run_behave_tests.bash
> +
- add shebang
- make file executable

2021-05-27 06:14 UTC, skhomuti commented on arenadata/scripts/run_behave_tests.bash
> +
done

2021-05-27 15:58 UTC, Maunty requested changes

2021-05-27 15:58 UTC, Maunty commented on arenadata/docker-compose.yaml
> +      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
ssh-keys or ssh_keys ? check your script

2021-07-05 06:43 UTC, skhomuti commented on gpMgmt/test/behave_utils/arenadata/fixtures.py
> +from behave import fixture
This file currently not used but will need for `concourse_cluster` tests later

2021-07-05 06:43 UTC, skhomuti commented on gpMgmt/test/behave/mgmt_utils/minirepro.feature
> +@minirepro @skip
Skip because these tests are broken

2021-07-05 06:43 UTC, skhomuti commented on gpMgmt/Makefile.behave
> +		PYTHONPATH=$$PYTHONPATH:$(PEXPECT_LIB):$(TEST_DIR) behave $(CURDIR)/test/behave/* -s -k --tags=$(tags) 2>&1 ; \
Changes for custom formatter support

2021-07-05 06:43 UTC, skhomuti commented on concourse/scripts/setup_gpadmin_user.bash
> +    find /home/gpadmin -not -group gpadmin -not -user gpadmin -print0 | xargs -P 0 -0 --no-run-if-empty chown --no-dereference gpadmin:gpadmin
It's dumb but it works and speed-up chown

2021-07-05 06:46 UTC, dgusakov commented on arenadata/readme.md
> +Before run tests you need docker-image
```suggestion
Before run tests you need to build a docker-image
```

2021-07-05 06:46 UTC, dgusakov commented on arenadata/readme.md
> +Tests are used `allure-behave` package and store allure output files in `allure-results` folder
```suggestion
Tests use `allure-behave` package and store allure output files in `allure-results` folder
```

2021-07-05 06:46 UTC, dgusakov commented on arenadata/readme.md
> +Pay attention that `allure-behave` has too old a version because it is compatible with `python2`.
```suggestion
**NOTE** that `allure-behave` has too old a version because it is compatible with `python2`.
```

2021-07-05 06:46 UTC, dgusakov commented on arenadata/readme.md
> +Docker containers have installed `sigar` libraries. It required only for `gpperfmon` tests.
```suggestion
Docker containers have installed `sigar` libraries. It is required only for `gpperfmon` tests.
```

2021-07-05 08:12 UTC, vgorkavenko approved these changes, later dismissed

2021-07-13 08:11 UTC, Maunty approved these changes

2021-07-13 08:14 UTC, Maunty requested changes

2021-07-13 08:14 UTC, Maunty commented on arenadata/docker-compose.yaml
> +      sysctl 'kernel.sem=500 1024000 200 4096' &&
https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime

2021-07-15 06:26 UTC, dgusakov commented on arenadata/docker-compose.yaml
> +      sysctl 'kernel.sem=500 1024000 200 4096' &&
@skhomuti take a look

2021-07-15 08:53 UTC, skhomuti commented on arenadata/docker-compose.yaml
> +      sysctl 'kernel.sem=500 1024000 200 4096' &&
fix

2021-07-16 07:56 UTC, Stolb27 commented on arenadata/scripts/behave_gpdb.bash
> +    rpm -i https://ci.arenadata.io/artifactory/ADB/6.7.1_arenadata4/centos/7/community/x86_64/sigar-headers-1.6.5-163.el7.x86_64.rpm &&
Maybe modify the Docker image to persist `sigar` to avoid duplication of these lines? I don't think that it's wanted behavior for regression tests.

2021-07-16 07:56 UTC, Stolb27 commented on arenadata/scripts/behave_gpdb.bash
> +    xz -d /home/gpadmin/sqldump/dump.sql.xz
Why we dump an empty database (cluster just created with `make_cluster`)? gpexpand tests expect complex database schema [produced](https://github.com/arenadata/gpdb/blob/3d6cc3d62b2b800bf72afa0d4a35333f4c543f00/concourse/scripts/ic_gpdb.bash#L80) by regression run.

2021-07-16 07:56 UTC, Stolb27 commented on arenadata/scripts/behave_gpdb.bash
> +    xz -d /home/gpadmin/sqldump/dump.sql.xz
I think we may either spaces or tabs in this function)

2021-07-21 07:43 UTC, skhomuti commented on arenadata/scripts/behave_gpdb.bash
> +    xz -d /home/gpadmin/sqldump/dump.sql.xz
https://arenadata.atlassian.net/browse/ADBDEV-1901 I suggest making the correct dump a separate task

2021-07-22 07:13 UTC, skhomuti commented on arenadata/scripts/behave_gpdb.bash
> +    rpm -i https://ci.arenadata.io/artifactory/ADB/6.7.1_arenadata4/centos/7/community/x86_64/sigar-headers-1.6.5-163.el7.x86_64.rpm &&
fixed

2021-07-22 11:55 UTC, Stolb27 commented on arenadata/docker-compose.yaml
> +    image: "hub.adsw.io/library/gpdb_regress:${BRANCH_NAME}"
image name has been renamed to gpdb6_regress since adb-5.x tests were implemented. Please check it.

2021-07-26 05:45 UTC, dgusakov approved these changes

2021-07-26 06:42 UTC, Stolb27 approved these changes

2021-07-26 06:58 UTC, Maunty approved these changes

2021-07-26 07:06 UTC, merged