Check if index pathkeys list is empty in find_usable_indexes() function
arenadata/db pull request #206
Opened 2021-06-08 12:47 UTC by seryozhasmirnov

index_pathkeys might be NULL when target index does not provide
a desired sort order in query or when useful for sorting index
corresponding to inherited or child relation does not participate
in join.

Due to that the following fragment fails:
```
    CREATE TABLE clstr_tst (a int, b INT) DISTRIBUTED BY (a);
    CREATE INDEX clstr_tst_b_c ON clstr_tst (b);
    CREATE TABLE clstr_tst_inh () INHERITS (clstr_tst);
    SELECT a FROM clstr_tst ORDER BY 1
```

The solution is to check if index_pathkeys list is empty before using it.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2021-06-11 09:34 UTC, InnerLife0 approved these changes, later dismissed
LGTM. _pathkeys_useful_for_ordering_ function implicitly used [near](https://github.com/arenadata/gpdb/blob/46ce6a35a6f217a97ee252b9d2b60bdafa75970a/src/backend/optimizer/path/indxpath.c#L451), already [takes care](https://github.com/arenadata/gpdb/blob/46ce6a35a6f217a97ee252b9d2b60bdafa75970a/src/backend/optimizer/path/pathkeys.c#L2144) about null _index_pathkeys_ list.

2021-06-21 04:25 UTC, darthunix requested changes
@seryozhasmirnov I have no questions to the current fix, but you should add regression tests to the current PR. Every fixed bug should produce a new regression test if possible.

2021-07-08 13:47 UTC, maksm90 commented
@seryozhasmirnov please, turn your attention to this PR - community is interested in this issue https://github.com/greenplum-db/gpdb/issues/12221. I think it's good time to present your patch there.

2021-07-08 17:53 UTC, seryozhasmirnov commented
> @seryozhasmirnov I have no questions to the current fix, but you should add regression tests to the current PR. Every fixed bug should produce a new regression test if possible.

Thank you, I will think about feasibility of adding test - it could be tricky as in fact there is no issue, the code works fine without assert.

2021-07-08 17:59 UTC, maksm90 commented
@seryozhasmirnov I think you have to bring your work out in thread so that Pivotal`s guys know that you are working on this issue and already have working patch.

2021-07-10 03:17 UTC, seryozhasmirnov commented
> @seryozhasmirnov I have no questions to the current fix, but you should add regression tests to the current PR. Every fixed bug should produce a new regression test if possible.

This test fixes the failed test 

> @seryozhasmirnov I have no questions to the current fix, but you should add regression tests to the current PR. Every fixed bug should produce a new regression test if possible.

@darthunix, I do not think that any new tests should be added. With this change the tests failed before now passes.

For example, `cluster` test was failing:

>   INSERT INTO clstr_tst (b, c, d) VALUES (6, 'seis', repeat('xyzzy', 100000));
  CLUSTER clstr_tst_c ON clstr_tst;
  SELECT a,b,c,substring(d for 30), length(d) from clstr_tst ORDER BY 1,2,3,4;
! FATAL:  Unexpected internal error (indxpath.c:436)
! DETAIL:  FailedAssertion("!(cdbpathlocus_is_valid(*_locus))", File: "indxpath.c", Line: 436)
! HINT:  Process 14390 will wait for gp_debug_linger=120 seconds before termination.
! Note that its locks and other resources will not be released until then.
! server closed the connection unexpectedly
!       This probably means the server terminated abnormally
!       before or while processing the request.
! connection to server was lost

So not it passes.

And this is not the only test. More tests started to pass.

2021-07-13 20:29 UTC, maksm90 reviewed
> As there is no indexes for child relation build_index_pathkeys
function returns 0x0 and due to that in CdbPathLocus_MakeHashed macro
assertion Assert(cdbpathlocus_is_valid(*_locus) fails because
partkey_h is set to partkey that is 0x0 and it is checked by
cdbpathlocus_is_valid function.

Your point about missing indexes for child relation in the context of assert failure is not correct. Assertion occurs when we process the parent table `clstr_tst` as with `reloptkind = RELOPT_OTHER_MEMBER_REL` (`relid = 2`). This could be verified by debugger at the frame 1 of failed assert:
```C
(gdb) p get_rel_name(root->simple_rte_array[rel->relid]->relid)
$12 = 0x5646467d9658 "clstr_tst"
```
This relation has 1 index:
```C
(gdb) p get_rel_name(index->indexoid)
$15 = 0x5646467d96a0 "clstr_tst_b_c"
```
But we cannot build `pathkey` structure (that represents sorting order) for that index (return NULL at [here](https://github.com/arenadata/gpdb/blob/ADBDEV-1458/src/backend/optimizer/path/indxpath.c#L405-L406)). This occurs because we cannot assign to this `pathkey` over indexed attribute the corresponding equivalence member object from global equivalence classes list (`root->eq_classes`). The `root->eq_classes` list doesn't merely contains indexed attribute `b`.
I might assume that we build single-item EquivalenceClass for pathkeys to represent a desired sort order in the query (for attribute `a` in our case). In this scenario we have to assign to `index_pathkeys` variable a NIL value. But the following query when we order by `b` (indexed attribute):
```sql
SELECT b FROM clstr_tst ORDER BY 1
```
also fails on the same assert: the EquivalenceClass for target parent relation (`relid = 2`) contains attribute `a` (not `b`).

@seryozhasmirnov I suggest you to get sense of EquivalenceClass semantics applicable to PathKey structure and figure out what the actual reason of failure in the queries above.

2021-07-15 05:03 UTC, darthunix commented
> `SELECT b FROM clstr_tst ORDER BY 1` also fails on the same assert

>  I suggest you to get sense of EquivalenceClass semantics applicable to PathKey structure and figure out what the actual reason of failure in the queries above.

@maksm90 thank you for that catch. I've made some research and found out that in our example we populate `EquivalenceClass` in `get_eclass_for_sort_expr()` with `create_it = true` option.
```
    frame #1: 0x000000010655cfcd postgres`make_pathkey_from_sortinfo(root=0x00007fea2d0540a0, expr=0x00007fea2d056798, ordering_op=97, nulls_first='\0', sortref=1, create_it='\x01', canonicalize='\0') at pathkeys.c:612:11
  * frame #2: 0x000000010655de58 postgres`make_pathkeys_for_sortclauses(root=0x00007fea2d0540a0, sortclauses=0x00007fea2d053968, tlist=0x00007fea2d0566c8, canonicalize='\0') at pathkeys.c:1407:13
    frame #3: 0x00000001065735d4 postgres`grouping_planner(root=0x00007fea2d0540a0, tuple_fraction=0) at planner.c:1468:4
    frame #4: 0x00000001065722d1 postgres`subquery_planner(glob=0x00007fea2c813b28, parse=0x00007fea2d053a50, parent_root=0x0000000000000000, hasRecursion='\0', tuple_fraction=0, subroot=0x00007ffee9b10780, config=0x00007fea2d054028) at planner.c:773:10
    frame #5: 0x00000001065710d0 postgres`standard_planner(parse=0x00007fea2d053a50, cursorOptions=0, boundParams=0x0000000000000000) at planner.c:295:13
    frame #6: 0x0000000106570cc0 postgres`planner(parse=0x00007fea2c813c60, cursorOptions=0, boundParams=0x0000000000000000) at planner.c:163:12
    frame #7: 0x000000010665e0e0 postgres`pg_plan_query(querytree=0x00007fea2c813c60, cursorOptions=0, boundParams=0x0000000000000000) at postgres.c:914:9
    frame #8: 0x000000010665e2aa postgres`pg_plan_queries(querytrees=0x00007fea2c8147a8, cursorOptions=0, boundParams=0x0000000000000000, needSnapshot='\0') at postgres.c:991:21
    frame #9: 0x0000000106662359 postgres`exec_simple_query(query_string="SELECT b FROM clstr_tst ORDER BY 1;", seqServerHost=0x0000000000000000, seqServerPort=-1) at postgres.c:1704:19
    frame #10: 0x000000010666078f postgres`PostgresMain(argc=1, argv=0x00007fea2d019b60, dbname="adb", username="darthunix") at postgres.c:4962:7
    frame #11: 0x00000001065de913 postgres`BackendRun(port=0x00007fea2e004140) at postmaster.c:6732:9
    frame #12: 0x00000001065dba2a postgres`BackendStartup(port=0x00007fea2e004140) at postmaster.c:6406:13
    frame #13: 0x00000001065d7171 postgres`ServerLoop at postmaster.c:2444:7
    frame #14: 0x00000001065d54cb postgres`PostmasterMain(argc=15, argv=0x00007fea2c5043c0) at postmaster.c:1528:11
    frame #15: 0x00000001064b8499 postgres`main(argc=15, argv=0x00007fea2c5043c0) at main.c:206:7
    frame #16: 0x00007fff20588f5d libdyld.dylib`start + 1
```
I suspend the problem is that in 5X we pass `expr` by [reference](https://github.com/arenadata/gpdb/blob/370be3e63496bfcdbb76b534154e0d3baea2596c/src/backend/optimizer/path/equivclass.c#L489) while in 6X we pass its [copy](https://github.com/arenadata/gpdb/blob/8136cfa3bce24082f65697416d7aaf666c8cddce/src/backend/optimizer/path/equivclass.c#L648). As a result we have only a single item in a [list](https://github.com/arenadata/gpdb/blob/370be3e63496bfcdbb76b534154e0d3baea2596c/src/include/nodes/relation.h#L203) of active `EquivalenceClasses` of `PlannerInfo`. It was fixed in https://github.com/arenadata/gpdb/commit/b310b6e31ce5 but I am not sure that we need the whole commit.

2021-07-15 10:41 UTC, maksm90 commented
Debug session on 6X have revealed that `EquivalenceClasses` list have to show all interesting for query sort orders. E.g., in the following query:
```sql
SELECT a, b FROM clstr_tst ORDER BY 1
```
where we sort by not indexed `a` but return alongside `b` we have `EquivalenceClass` over `a` for all (parent and child) relations:
```
# output from gdb command: p pprint(root->eq_classes)
(
   {EQUIVALENCECLASS 
   :ec_opfamilies (o 1976)
   :ec_collation 0 
   :ec_members (
      {EQUIVALENCEMEMBER 
      :em_expr 
         {VAR 
         :varno **1** 
         :varattno **1** 
         :vartype 23 
         :vartypmod -1 
         :varcollid 0 
         :varlevelsup 0 
         :varnoold 1 
         :varoattno 1 
         :location 7
         }
      :em_relids (b 1)
      :em_nullable_relids (b)
      :em_is_const false 
      :em_is_child false 
      :em_datatype 23
      }
      {EQUIVALENCEMEMBER 
      :em_expr 
         {VAR 
         :varno **2** 
         :varattno **1** 
         :vartype 23 
         :vartypmod -1 
         :varcollid 0 
         :varlevelsup 0 
         :varnoold 2 
         :varoattno 1 
         :location -1
         }
      :em_relids (b 2)
      :em_nullable_relids (b)
      :em_is_const false 
      :em_is_child true 
      :em_datatype 23
      }
      {EQUIVALENCEMEMBER 
      :em_expr 
         {VAR 
         :varno **3** 
         :varattno **1** 
         :vartype 23 
         :vartypmod -1 
         :varcollid 0 
         :varlevelsup 0 
         :varnoold 3 
         :varoattno 1 
         :location -1
         }
      :em_relids (b 3)
      :em_nullable_relids (b)
      :em_is_const false 
      :em_is_child true 
      :em_datatype 23
      }
   )
   :ec_sources <> 
   :ec_derives <> 
   :ec_relids (b 1)
   :ec_has_const false 
   :ec_has_volatile false 
   :ec_below_outer_join false 
   :ec_broken false 
   :ec_sortref 1
   }
   {EQUIVALENCECLASS 
   :ec_opfamilies (o 1976)
   :ec_collation 0 
   :ec_members (
      {EQUIVALENCEMEMBER 
      :em_expr 
         {VAR 
         :varno 2 
         :varattno 1 
         :vartype 23 
         :vartypmod -1 
         :varcollid 0 
         :varlevelsup 0 
         :varnoold 2 
         :varoattno 1 
         :location -1
         }
      :em_relids (b 2)
      :em_nullable_relids (b)
      :em_is_const false 
      :em_is_child false 
      :em_datatype 23
      }
   )
   :ec_sources <> 
   :ec_derives <> 
   :ec_relids (b 2)
   :ec_has_const false 
   :ec_has_volatile false 
   :ec_below_outer_join false 
   :ec_broken false 
   :ec_sortref 0
   }
)
```
And here we would have NULL `index_pathkeys` built for index on parent table.
But when we order by `b` we get `EquivalenceMember`s in the first `EquivalenceClass` on `b` attribute:
```
(
   {EQUIVALENCECLASS 
   :ec_opfamilies (o 1976)
   :ec_collation 0 
   :ec_members (
      {EQUIVALENCEMEMBER 
      :em_expr 
         {VAR 
         :varno **1** 
         :varattno **2** 
         :vartype 23 
         :vartypmod -1 
         :varcollid 0 
         :varlevelsup 0 
         :varnoold 1 
         :varoattno 2 
         :location 10
         }
      :em_relids (b 1)
      :em_nullable_relids (b)
      :em_is_const false 
      :em_is_child false 
      :em_datatype 23
      }
      {EQUIVALENCEMEMBER 
      :em_expr 
         {VAR 
         :varno **2** 
         :varattno **2** 
         :vartype 23 
         :vartypmod -1 
         :varcollid 0 
         :varlevelsup 0 
         :varnoold 2 
         :varoattno 2 
         :location -1
         }
      :em_relids (b 2)
      :em_nullable_relids (b)
      :em_is_const false 
      :em_is_child true 
      :em_datatype 23
      }
      {EQUIVALENCEMEMBER 
      :em_expr 
         {VAR 
         :varno **3** 
         :varattno **2** 
         :vartype 23 
         :vartypmod -1 
         :varcollid 0 
         :varlevelsup 0 
         :varnoold 3 
         :varoattno 2 
         :location -1
         }
      :em_relids (b 3)
      :em_nullable_relids (b)
      :em_is_const false 
      :em_is_child true 
      :em_datatype 23
      }
   )
   :ec_sources <> 
   :ec_derives <> 
   :ec_relids (b 1)
   :ec_has_const false 
   :ec_has_volatile false 
   :ec_below_outer_join false 
   :ec_broken false 
   :ec_sortref 1
   }
   {EQUIVALENCECLASS 
   :ec_opfamilies (o 1976)
   :ec_collation 0 
   :ec_members (
      {EQUIVALENCEMEMBER 
      :em_expr 
         {VAR 
         :varno 2 
         :varattno 1 
         :vartype 23 
         :vartypmod -1 
         :varcollid 0 
         :varlevelsup 0 
         :varnoold 2 
         :varoattno 1 
         :location -1
         }
      :em_relids (b 2)
      :em_nullable_relids (b)
      :em_is_const false 
      :em_is_child false 
      :em_datatype 23
      }
   )
   :ec_sources <> 
   :ec_derives <> 
   :ec_relids (b 2)
   :ec_has_const false 
   :ec_has_volatile false 
   :ec_below_outer_join false 
   :ec_broken false 
   :ec_sortref 0
   }
)
```

Put it in a nutshell, I suppose that 5X have to build `EquivalenceClass` similar to 6X, i.e. it has to contain `EquivalenceMember`s with `order by` attribute for parent `RELOPT_BASEREL` and other `RELOPT_OTHER_MEMBER_REL` relations. IMO the problem place is inside `make_pathkeys_for_sortclauses` as @darthunix pointed out (thanks for this).

2021-07-16 10:03 UTC, maksm90 commented
5X builds `EquivalenceClass` without `RELOPT_OTHER_MEMBER_REL` relations. 6X adds parent and child `RELOPT_OTHER_MEMBER_REL` relations inside `add_child_rel_equivalences()` function [under](https://github.com/greenplum-db/gpdb/blob/6.17.0/src/backend/optimizer/path/allpaths.c#L999-L1008) routine of size estimation for append relation `set_append_rel_size()`. @seryozhasmirnov I think we have to add the same `add_child_rel_equivalences()` call under `set_append_rel_pathlist()` - smth like the following:
```C
diff --git a/src/backend/optimizer/path/allpaths.c b/src/backend/optimizer/path/allpaths.c
index f7eda01cd8..313cbdeb2a 100644
--- a/src/backend/optimizer/path/allpaths.c
+++ b/src/backend/optimizer/path/allpaths.c
@@ -515,11 +515,9 @@ set_append_rel_pathlist(PlannerInfo *root, RelOptInfo *rel,
          * We have to make child entries in the EquivalenceClass data
          * structures as well.
          */
-        if (rel->has_eclass_joins)
-        {
+        if (rel->has_eclass_joins || has_useful_pathkeys(root, rel))
             add_child_rel_equivalences(root, appinfo, rel, childrel);
-            childrel->has_eclass_joins = true;
-        }
+        childrel->has_eclass_joins = rel->has_eclass_joins;
 
         /*
          * Note: we could compute appropriate attr_needed data for the
```
But the above fragment doesn't add child attributes to `EquivalenceClass`, @seryozhasmirnov I think you might use the patch above as starting point to continue work until completion.

2021-07-20 04:53 UTC, Stolb27 reviewed
What difference between previous and current solutions?

2021-07-20 23:12 UTC, maksm90 commented on arenadata/Dockerfile
> +ENV CONFIGURE_FLAGS="--with-gssapi --enable-debug --enable-depend --enable-cassert \
Odd change of Dockerfile

2021-07-20 23:12 UTC, maksm90 commented on src/backend/optimizer/path/indxpath.c
> +				* CDB: For appendrel child, pathkeys contain Var nodes in terms
Please, add that this case is also about parent relation, smth like "... For appendrel child **and parent**, pathkeys contain ... in termsof the baserel"

2021-07-20 23:12 UTC, maksm90 commented on src/backend/optimizer/path/indxpath.c
> +			 * to the query desired sort order or in case of inherited table.
I propose to rewrite as following:
```
index_pathkeys might be NULL when target index doesn't provide some desired sort order in query or when useful for sorting index corresponds to inherited or child relation not participating in join
```

2021-07-21 02:01 UTC, darthunix reviewed
Current solution has the same logic as the previous attempt does
```c
if (!index_pathkeys && rel->reloptkind == RELOPT_OTHER_MEMBER_REL)
```
but seems to have a worth style (as we add one more `if.. else` level in the code).

After some research in PG 8.4 code I think that we don't have any problems with equivalence classes here. If it was a vanilla PG we would simply end with `useful_pathkeys == NIL` after `truncate_useless_pathkeys ()` and skip this path
```c
                index_is_ordered = OidIsValid(index->fwdsortop[0]);
                if (index_is_ordered && possibly_useful_pathkeys &&
                        istoplevel && outer_rel == NULL)
                {
                        index_pathkeys = build_index_pathkeys(root, index,
                                                                                                  ForwardScanDirection);
                        useful_pathkeys = truncate_useless_pathkeys(root, rel,
                                                                                                                index_pathkeys);
                }
```
But GPDB adds a CDB specific code block with assumption that it is impossible not to have an index path for a child relation while its parent relation already has one. This is the main fault in this code and I vote to fix it in with a previous approach (but add additional comments with explanations).

2021-07-21 04:02 UTC, Stolb27 commented on arenadata/Dockerfile
> +ENV CONFIGURE_FLAGS="--with-gssapi --enable-debug --enable-depend --enable-cassert \
I request these changes to run tests against build with asserts. It's good to save these changes in a separate commit with an appropriate description.

2021-07-21 19:07 UTC, maksm90 approved these changes, later dismissed

2021-07-22 03:59 UTC, darthunix commented on src/backend/optimizer/path/indxpath.c
> +			 * CDB: For appendrel child and parent, pathkeys contain Var nodes
This comment is very difficult to understand. May be we should rewrite it? 

I suggest to keep the original comment logic but add an explanation why we check that `index_pathkeys` is not NULL. The reason is that it is possible for a child relation doesn't have an index path while the parent one has some. So it makes no sense try to transform the index pathkeys of the child relation to refer the parent columns as we don't have and index path at all.

2021-07-22 07:24 UTC, darthunix approved these changes

2021-07-22 07:40 UTC, maksm90 approved these changes

2021-07-22 09:09 UTC, merged