Fix gpperfmon fails
arenadata/db pull request #337
Opened 2022-05-30 06:08 UTC by At1ass

Disable BGWORKER_SHMEM_ACCESS flag for gpperfmon background process

2022-06-17 11:09 UTC, Stolb27 commented
@InnerLife0, take a look at this one? We've already discussed this fix sometimes. I've pushed empty commit with description to rerun tests on power also.

2022-06-27 17:12 UTC, InnerLife0 requested changes
@Stolb27 
Overall OK, except last commit message. Could you re-read it? There are some grammar shortcomings. Triple was, for example. I think you can review it and do better yourself.

2022-06-28 02:51 UTC, Stolb27 commented
@InnerLife0, I've reword **pull request** description, and I'm going to use it during commit squash with GitHub UI to avoid CI tests run. Is it better written for you?)

2022-06-28 05:28 UTC, InnerLife0 approved these changes

2022-07-06 08:41 UTC, merged