Fix xslice detection for subplans.
arenadata/db pull request #342
Opened 2022-06-06 18:52 UTC by InnerLife0

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

2022-06-17 10:09 UTC, Stolb27 requested changes

2022-06-17 10:09 UTC, Stolb27 commented on src/backend/cdb/cdbmutate.c
> +	PlannerInfo *root;
First structure item for `plan_tree_walker` must be `plan_tree_base_prefix` (see this structure usage). Your code will work, but may create hidden bugs in case of refactoring plan_tree_walker.

2022-06-17 10:09 UTC, Stolb27 commented on src/backend/cdb/cdbmutate.c
> +shareinput_walker(Node *node, ShareInputContext * ctx)
Did you apply pgindent for your code? Uneven space formatting around *.

2022-06-17 10:09 UTC, Stolb27 commented on src/backend/cdb/cdbmutate.c
> +			}
There is appropriate function `planner_subplan_get_root`. Am I correct?

2022-06-17 10:09 UTC, Stolb27 commented on src/backend/cdb/cdbmutate.c
> +				 * for GPDB, since we create a new copy of the subplan if two
Maybe don't touch comments if we don't modify them to decrease patch footprint?

2022-06-17 10:09 UTC, Stolb27 commented on src/test/regress/sql/shared_scan.sql
> +-- stable '100' as a result.
This test case is flaky on unpatched version `PostgreSQL 9.4.26 (Greenplum Database 6.20.1_arenadata33 build dev)`:

```
--- \/home\/givi\/src\/gpdb6\/src\/test\/regress\/expected\/shared_scan_optimizer\.out  2022-06-17 10:00:40.097407850 +0000
+++ \/home\/givi\/src\/gpdb6\/src\/test\/regress\/results\/shared_scan\.out     2022-06-17 10:00:40.107407885 +0000
@@ -356,10 +356,7 @@
 )
 select l.c from cte2 l
 left join t1 u on l.c = u.c;
- c 
----
-(0 rows)
-
+ERROR:  cannot execute inactive Motion (nodeMotion.c:264) (nodeMotion.c:264)
 -- This case shows wrong count(*) result on pre-patched version.
 -- Shared Scan consumer from slice1 not marked as cross-slice and used not
 -- initialized tuple store. We got '1' as the result of the query - only

======================================================================
```

2022-06-20 13:45 UTC, InnerLife0 commented on src/backend/cdb/cdbmutate.c
> +	PlannerInfo *root;
Yes, you are right.

2022-06-20 13:49 UTC, InnerLife0 commented on src/backend/cdb/cdbmutate.c
> +shareinput_walker(Node *node, ShareInputContext * ctx)
Yes. And that change was made by pgindent.

2022-06-20 13:50 UTC, InnerLife0 commented on src/backend/cdb/cdbmutate.c
> +			}
`planner_subplan_get_root` will fall to get out of range item.

2022-06-20 13:52 UTC, InnerLife0 commented on src/test/regress/sql/shared_scan.sql
> +-- stable '100' as a result.
It seems I was unclear. This test is flacky on old versions, because they miss new fault point. I'll change a comment.

2022-06-20 13:56 UTC, InnerLife0 commented on src/backend/cdb/cdbmutate.c
> +				 * for GPDB, since we create a new copy of the subplan if two
I preferred to refactor all the function including it's comments. A lot of changes were done and it's painful to keep function partially formatted in such case.

2022-06-21 02:36 UTC, Stolb27 commented on src/backend/cdb/cdbmutate.c
> +			}
Do you know cases when gpdb has a reference to not existing subplan?

2022-06-21 03:48 UTC, Stolb27 commented on src/test/regress/sql/shared_scan.sql
> +-- stable '100' as a result.
My bad. It was a stupid question.

2022-06-21 05:35 UTC, InnerLife0 commented on src/backend/cdb/cdbmutate.c
> +			}
This from `shared_scan.sql`
```
drop table if exists pk_list;
create table pk_list (id int, schema_name varchar, table_name varchar) distributed by (id);
drop table if exists calender;
create table calender (id int, data_hour timestamp) distributed by (id);

explain (costs off)
with
	tbls as (select distinct schema_name, table_name as table_nm from pk_list),
	tbls_daily_report_23 as (select unnest(string_to_array('mart_cm.card' ,',')) as table_nm_23),
	tbls_w_onl_actl_data as (select unnest(string_to_array('mart_cm.cont_resp,mart_cm.card', ',')) as table_nm_onl_act)
select  data_hour, stat.schema_name as schema_nm, dt.table_nm
from (
	select * from calender c
	cross join tbls
) dt
inner join (
	select tbls.schema_name, tbls.table_nm as table_name
	from tbls tbls
) stat on dt.table_nm = stat.table_name
where
	(data_hour = date_trunc('day',data_hour) and stat.schema_name || '.' ||stat.table_name not in (select table_nm_23 from tbls_daily_report_23))
	and (stat.schema_name || '.' ||stat.table_name not in (select table_nm_onl_act from tbls_w_onl_actl_data))
	or (stat.schema_name || '.' ||stat.table_name in (select table_nm_onl_act from tbls_w_onl_actl_data));
```

2022-06-21 05:37 UTC, InnerLife0 commented on src/backend/cdb/cdbmutate.c
> +			}
And this from `subselect_gp.sql`
```
CREATE TABLE foo_s (a integer, b integer)  PARTITION BY RANGE(b)
    (PARTITION sub_one START (1) END (10),
     PARTITION sub_two START (11) END (22));
INSERT INTO foo_s VALUES (9,9);
INSERT INTO foo_s VALUES (2,9);
CREATE TABLE bar_s (c integer, d character varying(10));
INSERT INTO bar_s VALUES (9,9);
CREATE TABLE baz_s (i int4);
INSERT INTO baz_s VALUES (9);

set optimizer=off;
SELECT bar_s.c FROM bar_s, foo_s WHERE foo_s.b = (SELECT max(i) FROM baz_s WHERE bar_s.c = 9) AND foo_s.b = bar_s.d::int4;
```

2022-06-21 08:12 UTC, Stolb27 commented on src/backend/cdb/cdbmutate.c
> +			}
We found out that the only case when subplans and subroots arrays have inconsistent length is fixup_subplans modification. We are going to fix this problem too.

2022-06-22 07:55 UTC, Stolb27 approved these changes

2022-07-06 09:15 UTC, merged