ADBDEV-697. Fix null transition for non-strict aggregate functions
arenadata/db pull request #61
Opened 2020-04-02 21:26 UTC by dursegov

The bug was indeed related to the case when pergroupstate->transValueIsNull is false, but pergroupstate->transValue = 0.
These fields correspond to an aggregate group and updated on HashAggTable insert:
agg_hash_initial_pass -> advance_aggregates -> advance_transition_function -> invoke_agg_trans_func

As can be seen new transValue is returned from int8_avg_combine(fcinfo) and transValueIsNull is set to fcinfo->isnull that is set to false by default. The problem that int8_avg_combinei() can return immediately the old transValue and not touch fcinfo->isnull at all if increment is null. So we can end up with transValueIsNull is false and transValue = 0. This is possible, because int8_avg_combine() is defined as strict function (transfn->fn_strict = true) and accept nulls. As another approach it is good to check if this flag is really required for this function.

2020-04-03 04:19 UTC, darthunix requested changes
I think the root of all problems is corrupted Datums in some aggregation state hash entries (no matter whether they were spilled or not).  So the goals of this PR should be:
1. Add asserting elogs in places where it can cause a segfault. We should not hide a problem, or we get wrong results in aggregation.
2. Try to find out the reason of this corruption.
At the moment this fix seems to be wrong (but I still have no idea about a place where aggregation state was corrupted)

2020-04-06 03:01 UTC, darthunix commented
I have compared results on the same data set for this patch on GP and on upstream PG - they return the same results.

2020-04-06 03:02 UTC, darthunix approved these changes

2020-04-15 07:43 UTC, deart2k commented
bender build

2020-04-15 07:58 UTC, merged