fix possible deadlocks between catalog update and FTS
arenadata/db pull request #66
Opened 2020-04-22 01:33 UTC by Stolb27

This problem partially fixed in #8012 (https://github.com/greenplum-db/gpdb/pull/8012)
However, these changes do not take into account the blocking mode of nested functions
for gp_add_segment_mirror (add_segment_config, add_segment_config_entry,
get_availableDbId). This functions still require AccessExclusiveLock mode.
Catalog changes are proccess in single transaction so this mode will be hold until
transaction commit. So we may get deadlock if we will be restore multiple segment
for cluster with large persistent tables longer then 30*2
(DISPATCH_WAIT_TIMEOUT_MSEC) seconds.

In general, any update catalog operations requiring dispatch may cause deadlock with FTS.
So fixed gp_add_master_standby too.

gp_add_segment does not dispatch, but is performed in one transaction with the update
of the mode and status of the segment, which require dispatching

6X and master not affected by this problem because not use dispatch for catalog changes.

PS I lock gp_persistent_relation_node in utlility mode on segment for reproduce problem.

2020-04-22 02:51 UTC, darthunix requested changes
I can suggest to modify comments in a code to
```
/*
 * We should avoid concurrent modifications of gp_segment_configuration
 * when read and add entries to this table. Using ExclusiveLock still
 * allows FTS probe to proceed if we request it ourselves. It can happen
 * in a case of a failure or timeout when QD polls results of 
 * add_segment_persistent_entries() from QEs.
 * Note that FTS acquires AccessShareLock to read from 
 * gp_segment_configuration and RowExclusiveLock to modify it.
 *
 * FIXME: deadlock will still happens if any other segment failes during
 * FTS probe requested by us.
 */
```

2020-04-22 03:37 UTC, Stolb27 commented
@darthunix , thank you. I changed that.

2020-04-22 05:43 UTC, darthunix approved these changes

2020-04-24 06:07 UTC, leskin-in approved these changes

2020-04-27 00:51 UTC, Stolb27 commented
Internal review. No need more.

2020-04-27 00:51 UTC, closed without merging