Fix checking for existing builtin overflow functions
arenadata/db pull request #958
Opened 2024-05-29 07:44 UTC by red1452

Fix checking for existing builtin overflow functions

This patch fixes commit 1ca5486573e414aa611ec5fd55a57590b85bf7f0, which added
support of using builtin overflow functions: __builtin_add_overflow,
__builtin_sub_overflow, __builtin_mul_overflow. The configure script tries to
compile a small program with one of these functions. Compilation was without any
errors, because to correctly check gcc requires flag
-Werror=implicit-function-declaration. This flag is added later.

This patch moves this check after flag -Werror=implicit-function-declaration is
added to CFLAGS.

2024-05-29 08:01 UTC, BenderArenadata commented
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1448913

2024-05-29 08:03 UTC, BenderArenadata commented
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1448912

2024-05-29 08:34 UTC, BenderArenadata commented
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1449011

2024-05-29 08:40 UTC, BenderArenadata commented
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1449013

2024-05-29 14:25 UTC, BenderArenadata commented
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1451507

2024-05-29 14:26 UTC, BenderArenadata commented
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1451506

2024-05-29 14:41 UTC, Stolb27 requested changes
You mustn't modify configure file by hands. Modify configure.in and regenerate configure file, instead.

2024-05-29 17:45 UTC, BenderArenadata commented
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1451993

2024-05-29 17:52 UTC, BenderArenadata commented
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1451994

2024-05-30 11:51 UTC, BenderArenadata commented
Failed job Build for x86_64: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1455592

2024-05-30 11:57 UTC, BenderArenadata commented
Failed job Build for ppc64le: https://gitlab.adsw.io/arenadata/github_mirroring/gpdb/-/jobs/1455593

2024-05-30 11:58 UTC, InnerLife0 approved these changes

2024-05-30 12:06 UTC, merged